server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 定义从注册中心获取注册服务的时间间隔
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: DOHKO-EUREKA-CLIENT-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: DOHKO-EUREKA-CLIENT-ORDER-SERVICE
        uri: lb://DOHKO-EUREKA-CLIENT-ORDER-SERVICE
        predicates:
        - Path=/order-service/**
        filters:
        - StripPrefix=1